CC = python3
SOURCE = __main__.py
CLEAR = clear && clear &&
INPUT = input.txt
TEMPLATE = template.py

all:
	$(CLEAR) $(CC) $(SOURCE)
runfile:
	$(CLEAR) $(CC) $(SOURCE) < $(INPUT)
init:
	echo | cat $(TEMPLATE) > $(SOURCE)
